export const categories = {
  painting: { label: "Painting", color: "#C17767", definition: "Narrative and decorative image-making, often rooted in local materials, ritual storytelling, and inherited visual languages." },
  textile: { label: "Textile & Weave", color: "#4A6C6F", definition: "Art made through thread, loom, dye, and surface pattern. Textiles carry memory, status, devotion, and regional identity through everyday use." },
  dance: { label: "Dance", color: "#D6A254", definition: "Embodied storytelling shaped by rhythm, gesture, music, and oral transmission. Dance keeps mythology and community history moving through generations." },
  theatre: { label: "Theatre & Music", color: "#685044", definition: "Performing traditions that combine voice, instrument, costume, stagecraft, and narrative to turn shared histories into living events." },
  craft: { label: "Craft & Sculpture", color: "#8B9582", definition: "Skilled making in clay, metal, wood, stone, and natural materials. These practices connect utility, ceremony, ecology, and hand knowledge." }
};

export const traditions = [
  { name: "Madhubani art", displayName: "Madhubani Painting", category: "painting", region: "Mithila, Bihar", coords: [26.35, 86.08], image: "Madhubani", summary: "Madhubani painting grew from ritual wall and floor images made by women of the Mithila region. Its dense lines, flat color, and symbolic fish, birds, and deities create a vivid visual grammar. The form carries domestic knowledge and celebrates festivals, fertility, and local ecology." },
  { name: "Warli painting", displayName: "Warli Painting", category: "painting", region: "Palghar, Maharashtra", coords: [19.70, 72.77], image: "Warli", summary: "Warli painting comes from the Warli communities of Maharashtra and traditionally appeared on the walls of homes during marriage ceremonies. Simple white figures made from rice paste move through scenes of farming, hunting, music, and ritual. Its geometric visual language turns community life into a shared record." },
  { name: "Kalamkari", displayName: "Kalamkari", category: "painting", region: "Machilipatnam, Andhra Pradesh", coords: [16.18, 81.13], image: "Kalamkari", summary: "Kalamkari means ‘drawing with a pen’ and refers to hand-painted or block-printed cotton. Artisans build intricate mythological scenes with natural dyes, using a bamboo or date-palm pen. The textile tradition remains closely linked to temple storytelling and trade." },
  { name: "Pattachitra", displayName: "Pattachitra", category: "painting", region: "Raghurajpur, Odisha", coords: [19.88, 85.83], image: "Pattachitra", summary: "Pattachitra is a disciplined cloth-based painting tradition from Odisha, known for strong outlines and ornamental borders. Artists prepare a smooth tamarind-seed-coated surface before painting stories of Jagannath and Krishna. Each image is both devotional object and carefully preserved visual narrative." },
  { name: "Gond art", displayName: "Gond Art", category: "painting", region: "Dindori, Madhya Pradesh", coords: [22.95, 81.08], image: "Gond Art", summary: "Gond artists translate stories of forests, animals, ancestors, and village life into rhythmic patterns and luminous dots. The contemporary form grows from mural traditions of the Gond people. It expresses a worldview in which humans, animals, and landscape remain deeply interdependent." },
  { name: "Phad painting", displayName: "Phad Painting", category: "painting", region: "Shahpura, Rajasthan", coords: [25.62, 74.92], image: "Phad", summary: "Phad is a long painted scroll used by itinerant Bhopas to narrate the heroic deeds of folk deities. Its saturated colors and crowded scenes are designed to be read as the story unfolds. Painting, performance, and oral history work together as one tradition." },
  { name: "Pashmina", displayName: "Pashmina Weaving", category: "textile", region: "Srinagar, Kashmir", coords: [34.08, 74.79], image: "Pashmina", summary: "Pashmina shawls are woven from the fine under-fleece of Himalayan goats, prized for exceptional warmth and softness. Kashmiri artisans spin, weave, dye, and sometimes embroider the fiber with extraordinary patience. The craft reflects mountain ecology, historic trade routes, and generations of specialized skill." },
  { name: "Banarasi sari", displayName: "Banarasi Silk", category: "textile", region: "Varanasi, Uttar Pradesh", coords: [25.32, 83.01], image: "Banarasi Silk", summary: "Banarasi silk is famed for brocaded patterns woven with gold and silver zari. Designs often carry floral butis, Mughal-inspired ornament, and ceremonial symbolism. The sari’s elaborate making sustains a living loom culture at the heart of Varanasi." },
  { name: "Embroidery of India", displayName: "Kutch Embroidery", category: "textile", region: "Kutch, Gujarat", coords: [23.73, 69.86], image: "Kutch", summary: "Kutch embroidery encompasses distinct stitch and mirror-work traditions practiced by communities across Gujarat. Brilliant geometric surfaces decorate clothing, dowry textiles, and objects for daily life. Motifs act as markers of place, community, celebration, and a maker’s individual hand." },
  { name: "Chikan (embroidery)", displayName: "Chikankari", category: "textile", region: "Lucknow, Uttar Pradesh", coords: [26.85, 80.95], image: "Chikankari", summary: "Chikankari is a delicate white-on-white embroidery associated with Lucknow and its refined courtly history. Needleworkers create shadow-like textures, floral jaalis, and fine linear stitches on cotton, silk, or georgette. The quiet surface rewards close looking and preserves a sophisticated textile vocabulary." },
  { name: "Kantha", displayName: "Kantha Stitch", category: "textile", region: "Bengal, West Bengal", coords: [22.57, 88.36], image: "Kantha", summary: "Kantha began as a way to layer and reuse worn saris with simple running stitches. Makers transformed practical quilts into expressive surfaces filled with animals, flowers, figures, and remembered scenes. The tradition embodies care, resourcefulness, and women’s domestic storytelling." },
  { name: "Bharatanatyam", displayName: "Bharatanatyam", category: "dance", region: "Thanjavur, Tamil Nadu", coords: [10.79, 79.14], image: "Bharatanatyam", summary: "Bharatanatyam developed in the temples and courts of Tamil Nadu through a precise language of hand gestures, facial expression, rhythmic footwork, and sculptural poses. Its repertoire draws heavily on devotional poetry and classical music. Today it is both a major stage form and a living link to South Indian ritual culture." },
  { name: "Kathak", displayName: "Kathak", category: "dance", region: "Lucknow, Uttar Pradesh", coords: [26.85, 80.95], image: "Kathak", summary: "Kathak grew from the storytelling work of travelling kathakars and later flourished in Mughal and regional courts. Dancers combine rapid spins, intricate footwork, gesture, and expressive narrative with tabla and sarangi. Its layered history makes the form a meeting point of Hindu and Muslim cultural worlds." },
  { name: "Chhau dance", displayName: "Chhau Dance", category: "dance", region: "Mayurbhanj, Odisha", coords: [21.93, 86.73], image: "Chhau", summary: "Chhau is a vigorous masked dance-theatre tradition found across Odisha, Jharkhand, and West Bengal. Its expansive leaps and martial movement bring stories from epics, local legends, and nature to life. The form is performed in seasonal festivals where music, craft, and community gather together." },
  { name: "Ghoomar", displayName: "Ghoomar", category: "dance", region: "Udaipur, Rajasthan", coords: [24.58, 73.68], image: "Ghoomar", summary: "Ghoomar is a graceful communal dance traditionally performed by women in Rajasthan. Long skirts create concentric waves as dancers turn to the pulse of dhol and folk song. It is associated with celebration, welcome, and the social fabric of desert communities." },
  { name: "Yakshagana", displayName: "Yakshagana Theatre", category: "theatre", region: "Udupi, Karnataka", coords: [13.34, 74.75], image: "Yakshagana", summary: "Yakshagana is an overnight dance-theatre tradition from coastal Karnataka, combining sung narration, percussion, dialogue, and spectacular makeup. Performers improvise within stories drawn from the Mahabharata and other epics. Its open-air performances make mythology a communal, highly physical event." },
  { name: "Carnatic music", displayName: "Carnatic Music", category: "theatre", region: "Chennai, Tamil Nadu", coords: [13.08, 80.27], image: "Carnatic Music", summary: "Carnatic music is a classical South Indian tradition organized through raga, tala, and an enormous repertoire of composed and improvised pieces. Voice, veena, violin, and mridangam meet in performances built on deep listening. The music carries devotional poetry while remaining a sophisticated system of creative exploration." },
  { name: "Koodiyattam", displayName: "Koodiyattam", category: "theatre", region: "Thrissur, Kerala", coords: [10.52, 76.21], image: "Koodiyattam", summary: "Koodiyattam is one of India’s oldest surviving Sanskrit theatre traditions, performed in Kerala temple theatres. Actors use precise eye movement, hand gestures, chant, and elaborate facial expression to unfold a scene slowly. Its ritual context and demanding training preserve a rare performance language." },
  { name: "Baul", displayName: "Baul Music", category: "theatre", region: "Birbhum, West Bengal", coords: [23.84, 87.62], image: "Baul Music", summary: "Baul singers are itinerant mystics whose songs seek the divine within the human body rather than in institutions. Their music pairs poetic philosophy with an earthy voice, ektara, and hand percussion. The tradition’s radical openness has made it a defining part of Bengal’s cultural imagination." },
  { name: "Dhokra", displayName: "Dhokra Craft", category: "craft", region: "Bastar, Chhattisgarh", coords: [19.07, 81.95], image: "Dhokra", summary: "Dhokra is a lost-wax metal casting tradition practiced by artisan communities across central and eastern India. A wax model is layered with clay, fired, and replaced by molten brass to create distinctive textured figures. Ritual objects, animals, and musicians connect the craft to folk belief and everyday life." },
  { name: "Blue Pottery of Jaipur", displayName: "Jaipur Blue Pottery", category: "craft", region: "Jaipur, Rajasthan", coords: [26.91, 75.79], image: "Blue Pottery", summary: "Jaipur blue pottery is an unusual low-fired craft made from quartz, glass, and gum rather than ordinary clay. Cobalt blue, turquoise, and floral ornament give its vessels an instantly recognizable surface. The technique reflects a long history of Persian, Central Asian, and Rajasthani exchange." },
  { name: "Wood carving", displayName: "Wood Carving", category: "craft", region: "Srinagar, Kashmir", coords: [34.08, 74.79], image: "Wood Carving", summary: "Kashmiri wood carving turns walnut and other local woods into panels, furniture, and architectural surfaces of exceptional detail. Artisans use chisels to build floral arabesques, vines, and geometric relief. The craft echoes the region’s gardens, architecture, and centuries of refined handwork." },
  { name: "Bankura horse", displayName: "Terracotta Horses", category: "craft", region: "Bankura, West Bengal", coords: [23.23, 87.07], image: "Terracotta Horses", summary: "Bankura’s elongated terracotta horses are among Bengal’s most recognizable craft forms. Shaped by hand and fired in local kilns, they serve as offerings and emblems of strength, protection, and village identity. Their stylized silhouettes show how ritual objects can become icons of modern design." },
  { name: "Bidriware", displayName: "Bidriware", category: "craft", region: "Bidar, Karnataka", coords: [17.91, 77.52], image: "Bidriware", summary: "Bidriware is a metal inlay craft from Bidar, made by engraving a dark zinc alloy and filling the grooves with silver. The contrast between blackened metal and luminous inlay gives trays, boxes, and vessels their signature depth. Its technique records the Deccan’s layered Persianate and Indian histories." }
];
